[project]
name = "nwt-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "apache-airflow>=2.10.4",
    "dbt-core>=1.9.1",
    "dbt-postgres>=1.9.0",
    "pandas==2.0",
    "sqlalchemy>=1.4.54",
]
